include: 
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

bloc:
  rules:
    - avoid_build_context_extensions
    - avoid_flutter_imports
    - avoid_public_bloc_methods
    - avoid_public_fields
    - prefer_bloc
    - prefer_build_context_extensions
    - prefer_cubit
    - prefer_file_naming_conventions
    - prefer_void_public_cubit_methods

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
